services:
  postfix:
    image: quay.io/elnissi-io/postfix:0.2.4
    restart: unless-stopped
    environment:
      PRIMARY_DOMAIN: dev.elnissi.io
      RELAY_IP: 0.0.0.0/24
      AUTHS_FILE: /config/auths.yaml
      # SSL_CERT_FILE: /config/certs/key.pem
      # SSL_KEY_FILE: /config/certs/key.pem
      # OPENDKIM_DEFAULT_SELECTOR: mail
    # networks:
    #   front:
    #     ipv4_address: 172.16.202.2
    ports:
      - "25:25"
    #  - "587:587"
    #  - "993:993"
    volumes:
      - ./data/auths.yaml:/config/auths.yaml
      - ./data/mail.private:/etc/opendkim/keys/dev.elnissi.io/mail.private