services:
  postfix:
    image: quay.io/elnissi-io/postfix:0.1.1
    init: true
    restart: always
    environment:
      PRIMARY_DOMAIN: example.com
      RELAY_IP: 172.16.202.0/24
      AUTHS_FILE: /config/auths.yaml
      # SSL_CERT_FILE: /config/certs/key.pem
      # SSL_KEY_FILE: /config/certs/key.pem
      # OPENDKIM_DEFAULT_SELECTOR: mail
    # networks:
    #   front:
    #     ipv4_address: 172.16.202.2
    ports:
      - "25:25/tcp"
      - "587:587/tcp"
      - "993:993/tcp"
    volumes:
      - ./data/mail.private:/etc/opendkim/keys/example.com/mail.private


# networks:
#   front:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.16.202.0/24
