services:
  postfix:
    image: quay.io/elnissi-io/postfix
    init: true
    restart: always
    environment:
      PRIMARY_DOMAIN: example.com
      RELAY_IP: 172.16.202.1/32
      AUTHS_FILE: /config/auths.yaml
    networks:
      front:
        ipv4_address: 172.16.202.2
    ports:
      - "1025:25/tcp"
      - "1587:587/tcp"
      - "1993:993/tcp"
    secrets:
      - ssl_cert
      - ssl_key

secrets:
  ssl_cert:
    file: ./config/certs/fullchain.pem
  ssl_key:
    file: ./config/certs/privkey.pem

networks:
  front:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.202.0/24
