name: Build postfix image

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow on tag push that starts with 'v'
    paths-ignore:
      - README.md
      - docker-compose.yml
      - .github/**
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - docker-compose.yml
      - .github/**
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER_POSTFIX }}
          password: ${{ secrets.QUAY_TOKEN_POSTFIX }}

      - name: Extract Version from Tag
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_ENV

      - name: Build (and optionally push) image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: quay.io/elnissi-io/postfix:${{ env.VERSION }}  # Use the extracted version from tag

